name: Generate Documentation

on:  # whenever a release is published,
  release:
    types: [published]

jobs:  # update the docs.
  update-docs:
    runs-on: ubuntu-latest
    steps:

      # setup: checkout docugen tool and docs from github
      - name: checkout docugen repo
        uses: actions/checkout@v2
        with:
          repository: wandb/docugen
          path: documentation/docugen
          persist-credentials: false
      - name: checkout gitbook repo
        uses: actions/checkout@v2
        with:
          repository: wandb/gitbook
          path: documentation/gitbook
          ref: en
          persist-credentials: false
      # setup: bring in python plus the requirements for generating docs
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: setup python environment
        run: python -m pip install -r ./documentation/docugen/requirements.txt

      # generate the docs from the latest client library and overwrite gitbook contents
      - name: generate documentation
        working-directory: ./documentation/docugen
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: python generate.py --template_file ../gitbook/SUMMARY.md --commit_id $VERSION --output_dir ../gitbook
      # for debugging/tracking, display the generated table of contents
      - name: display ToC
        run: cat ./documentation/gitbook/SUMMARY.md

      # stage: commit the changes
      - name: commit changes
        working-directory: ./documentation/gitbook
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A .
          git commit -m "update reference docs to $VERSION"

      # deploy: push to the gitbook repository, en branch
      - name: push
        working-directory: ./documentation/gitbook
        env:
          PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          git remote set-url origin https://charlesfrye:$PERSONAL_ACCESS_TOKEN@github.com/wandb/gitbook.git
          git remote get-url origin
          git push --set-upstream origin en
